# === Database MỚI ===
spring.application.name=RECIPE-SERVICE
# Database này sẽ tự động được tạo nếu chưa có
spring.datasource.url=jdbc:mysql://localhost:3306/recipes_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=rootpass

# Cấu hình JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# === Port MỚI ===
# Chạy service này trên port 8081
server.port=8081

# === THÊM CỤC NÀY (Để gọi "Tổng đài") ===
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.prefer-ip-address=true
#eureka.client.enabled=false
recipe.upload-dir=/upload/recipe
spring.web.resources.static-locations=file:/upload/
spring.mvc.static-path-pattern=/uploads/**

user.service.url=http://user-service:8080/api/v1/users/
server.error.include-message=always
server.error.include-binding-errors=always
# ================== GEMINI AI CONFIG ==================
# Lấy API Key từ Google AI Studio
gemini.api.key=AIzaSyCzhYf6zfELIp9RSeK69JOn_DAtzWRP_ic
# URL cho model gemini-pro
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Gemini dùng cho gợi ý bài viết (thay Cohere)
gemini.suggestion.key=AIzaSyBts9M9In2808S94ryUvyASmvGHRShL6AI
gemini.suggestion.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

