# === Port chuẩn của Eureka ===
server.port=8761

# Tên của "Tổng đài"
spring.application.name=discovery-service

# === Cấu hình quan trọng ===
# Tắt chế độ "client" của Eureka.
# Vì đây là "Tổng đài", nó không cần phải đăng ký với chính nó.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false