# === Tên của service (QUAN TRỌNG) ===
# (Phải viết HOA và có gạch nối)
spring.application.name=USER-SERVICE
server.port=8080
# Cấu hình kết nối MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/users_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=rootpass
# Cấu hình JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cấu hình JWT
jwt.secret-key=DangQuyToan23102004LuuThiKimYen19032004
jwt.expiration-ms=86400000
# 1 ngày

# === THÊM CỤC NÀY (Để gọi "Tổng đài") ===
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.prefer-ip-address=true
#eureka.client.enabled=false

# === Upload Config (avatar user) ===
user.upload-dir=/upload/user
spring.web.resources.static-locations=file:/upload/
spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=file:/upload/user/
# Đường dẫn web để truy cập file tĩnh
spring.mvc.static-path-pattern=/uploads/user/**
# Thư mục trên ổ đĩa nơi lưu trữ file
spring.web.resources.static-locations=file:${user.upload-dir}/
spring.mvc.static-path-pattern=/uploads/user/**